<a href="https://colab.research.google.com/github/VietHoangg03/Machine_Learning_Basic/blob/main/NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learn Numpy Array

List vs NumPy Array
Đối tượng đang tìm hiểu là Array
Vector biểu diễn không gian 2 chiều hay 3 chiều => Array biểu diễn vector. Array để lưu trữ hay lưu trữ không gian nhiều chiều như ảnh 2 chiều, ảnh RGB 3 chiều.

NumPy Array nó cũng lưu chữ các item, nhưng các phần tử nó giống nhau về loại.

In [ ]:
# Ví dụ List chứa nhiều kiểu dữ liệu trong lst
lst = ["AOI", 2025, 3.14, -1, True, [1,2,3]]
print(lst)

['AOI', 2025, 3.14, -1, True, [1, 2, 3]]


In [ ]:
n=5
lst_zeros = [0]*n
print(lst_zeros) #cách tạo list

[0, 0, 0, 0, 0]


In [ ]:
#Tạo list Numpy

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr[3])

[1 2 3 4]
4


In [ ]:
# Tạo list Numpy bằng zero
n=5
arr_zeros = np.zeros(n)
print(arr_zeros)

[0. 0. 0. 0. 0.]


In [ ]:
# Tạo list Numpy bằng list cùng kiểu
# Nếu list khác kiểu sẽ không tạo được bằng list
lst = [2, 3, 5]
arr_from_lst = np.array(lst)
print(arr_from_lst)

[2 3 5]


In [ ]:
a_data = np.array([4,5,6,7,8,9,10,11,12,13,14,15,16])

print(a_data[1]) #1
print(a_data[-4]) #6

print(a_data[0:6:2]) #start=5, end=9, step=2
print(a_data[:7])
print(a_data[7:])
print(a_data[::2])

5
13
[4 6 8]
[ 4  5  6  7  8  9 10]
[11 12 13 14 15 16]
[ 4  6  8 10 12 14 16]


In [ ]:
# Hàm append
# Với list thì cú pháp: list.append
# Với numpy thì cú pháp là: np.append(a_data, 0)
a_data = np.array([4,5,6,7,8,9,10,11,12,13,14,15,16])
a_data = np.append(a_data,0)
print(a_data)

a_data[1] = 2
print(a_data)

a_data = np.append(a_data, [2,5])
print(a_data)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16  0]
[ 4  2  6  7  8  9 10 11 12 13 14 15 16  0]
[ 4  2  6  7  8  9 10 11 12 13 14 15 16  0  2  5]


In [ ]:
lst = [1, 2, 3]

def add_list(lst, a): #inplace
  lst = lst + [a]
  return lst

add_list(lst, 10) #Không có lst hứng nên không thay đổi lst gốc
print(lst)

lst = add_list(lst,10) # Đã hứng kết quả nên thay đổi
print(lst)


#Non inplace
def add_list2(lst, a):
  lst[len(lst):] = [a] #t

add_list2(lst, 10)
print(lst)





# Cộng list
lst1 = [1,2,3]
lst2 = [4,5,6]
print(lst1+lst2)

# Nhân list
lst1 = lst1*3
print(lst1)

[1, 2, 3]
[1, 2, 3, 10]
[1, 2, 3, 10, 10]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [64]:
#Sorting
arr=np.array([2,3,8,4,5,9,10,22,15])

arr.sort()
print(arr)

arr.sort()
arr = arr[::-1]
print(arr)

[ 2  3  4  5  8  9 10 15 22]
[22 15 10  9  8  5  4  3  2]


In [81]:
# delete, pop, remove
arr = np.array([2,3,8,4,5,9,10,22,15])
arr = np.delete(arr, 2) #Xoá 8
print(arr)

# Tìm vị trí để xoá
del_indice = np.where(arr == 9)
del_indice

arr = np.delete(arr, del_indice)
print(arr)


# Bỏ các phần tử của nhiều index
arr = np.delete(arr, np.arange(1,3))
print(arr)

# Dùng concate để bỏ
arr = np.array([2,3,8,4,5,9,10,22,15])
arr = np.concatenate([arr[:1], arr[3:]])
print(arr)


arr = np.array([2,3,8,4,5,9,10,22, 5,15])
print(np.where(arr == 5))

[ 2  3  4  5  9 10 22 15]
[ 2  3  4  5 10 22 15]
[ 2  5 10 22 15]
[ 2  4  5  9 10 22 15]
(array([4, 8]),)


In [82]:
x = np.array([1,2,3])
y = x

y[-1] = 1000 # Nó là view thôi nếu thay đổi y thì sẽ thay đổi cả x

print(x)
print(y)

[   1    2 1000]
[   1    2 1000]


In [86]:
arr = np.array([2,3,8,4,5,9,10,22, 5,15])

arr == 5

np.sum(arr == 5) #Kiểm tra xem có bao nhiêu phần tử 5

print(len(arr))
print(np.min(arr))
print(np.max(arr))
print(arr.shape)

10
2
22
(10,)


In [92]:
# Hàm zip
l1 = [1, 3, 4]
l2 = [3, 4, 5]

for i,j in zip(l1, l2):
  print(i,j)


# Hàm zip trong numpy không có nên sẽ dùng Zip-like dstack
l3 = np.array([1, 3, 4])
l4 = np.array([4, 5, 6])

zip_arr = np.dstack((l3,l4))

for i in zip_arr[0]:
  print(i)

  # => Dùng zip sẽ tiện hơn

1 3
3 4
4 5
[1 4]
[3 5]
[4 6]


In [94]:
#List enumerate
data = [1,4,5]
length = len(data)
for index in range(length):
  print(index, data[index]) # In ra index và giá trị



# Đối với array
arr = np.array([1, 3, 4])
np.ndenumerate(arr)

for index, value in np.ndenumerate(arr):
  print(index, value)

0 1
1 4
2 5
(0,) 1
(1,) 3
(2,) 4


In [98]:
arr = np.array([2,3,8,4,5,9,10,22, 5,15])

arr % 2 == 0

print(np.sum(arr[arr % 2 == 0])) # Tổng phần tử chia hết cho 2

even_arr = arr[arr % 2 == 0]
print(even_arr)


46
[ 2  8  4 10 22]


In [99]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(array_2d.shape)

(3, 3)


In [103]:
print(array_2d[1,1])
print(array_2d[2][1])

5
8


In [106]:
arr = np.array([[1,2], [2,3] , [3,4]])
print(arr.shape)

print(arr)

print(arr.reshape(2,3))

(3, 2)
[[1 2]
 [2 3]
 [3 4]]
[[1 2 2]
 [3 3 4]]


In [109]:
# Broadcasting and Vectoriazation
a = np.array([[1,2], [3,4], [5,6]])
print("array a:\n", a)

b = np.array([1,2])
print("array b:\n", a)

c = a + b
print(c)

print(c.ndim) #Chiều của mảng

array a:
 [[1 2]
 [3 4]
 [5 6]]
array b:
 [[1 2]
 [3 4]
 [5 6]]
[[2 4]
 [4 6]
 [6 8]]
2


In [114]:
#Stack 2 mảng với nhau
arr1 = np.arange(10).reshape((2,-1))

arr2 = np.repeat(8,10).reshape((2,-1))

print(arr1)
print(arr2)


#method1
new_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenated array:\n", new_arr)

#method2
new_arr = np.vstack((arr1, arr2))
print("Veritally Stack arrays: \n", new_arr)

#method theo phương ngang
new_arr = np.concatenate((arr1, arr2), axis=1)
print("Concatenated array ngang:\n", new_arr)

new_arr = np.hstack((arr1, arr2))
print("Horizontally Stack arrays: \n", new_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[8 8 8 8 8]
 [8 8 8 8 8]]
Concatenated array:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [8 8 8 8 8]
 [8 8 8 8 8]]
Veritally Stack arrays: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [8 8 8 8 8]
 [8 8 8 8 8]]
Concatenated array ngang:
 [[0 1 2 3 4 8 8 8 8 8]
 [5 6 7 8 9 8 8 8 8 8]]
Horizontally Stack arrays: 
 [[0 1 2 3 4 8 8 8 8 8]
 [5 6 7 8 9 8 8 8 8 8]]


In [118]:
arr = np.array([1,2,4,5,11,6,2,4,6,9,2,22,26,6,8,4,7])

idx = np.where(arr < 7)
print(idx)

out = arr[idx]
print(out)

(array([ 0,  1,  2,  3,  5,  6,  7,  8, 10, 13, 15]),)
[1 2 4 5 6 2 4 6 2 6 4]


In [120]:
arr1 = np.array([3,1,5,2,1,6,7,4,5,6]).reshape((2,-1))
arr2 = np.arange(10).reshape((2,-1))

out = np.where(arr1 > arr2, arr1, arr2)

print(out)

[[3 1 5 3 4]
 [6 7 7 8 9]]
